In [1]:
import numpy as np

In [2]:
np?

Type:        module
String form: <module 'numpy' from '/Users/henrybutler/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
File:        ~/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>

In [4]:
a = [1, 2, 3]

a_arr = np.array(a)

a_arr

array([1, 2, 3])

In [5]:
type(a_arr)

numpy.ndarray

In [6]:
print(f'Shape: {a_arr.shape}')

print(f'Size: {a_arr.size}')

print(f'dtype: {a_arr.dtype}')

Shape: (3,)
Size: 3
dtype: int64


In [7]:
X = [[1, 2, 3], [4, 5, 6]]

X_arr = np.array(X)

X_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(f"Shape: {X_arr.shape}") # How the entries are arranged
print(f"Size: {X_arr.size}") # How many entries
print(f"dtype: {X_arr.dtype}") # What type of entries


Shape: (2, 3)
Size: 6
dtype: int64


In [9]:
# A complicated example
# ALL sublists must be the same length (in this case, length 3)

Y = [
    [[1.1, 2.3, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
]

Y_arr = np.array(Y)

Y_arr

array([[[ 1.1,  2.3,  3. ],
        [ 4. ,  5. ,  6. ]],

       [[ 7. ,  8. ,  9. ],
        [10. , 11. , 12. ]]])

In [10]:
print(f"Shape: {Y_arr.shape}") # How the entries are arranged
print(f"Size: {Y_arr.size}") # How many entries
print(f"dtype: {Y_arr.dtype}") # What type of entries


Shape: (2, 2, 3)
Size: 12
dtype: float64


In [11]:
X_one_dim = np.array([1, 2, 3, 4])

X_two_dim = np.array([[1, 2, 3,], [4, 5, 6]])

In [12]:
print(X_one_dim)
print(X_one_dim + 5)

[1 2 3 4]
[6 7 8 9]


In [13]:
print(X_one_dim)
print(X_one_dim ** 2)

[1 2 3 4]
[ 1  4  9 16]


In [14]:
print(X_one_dim)
print(X_one_dim % 2)

[1 2 3 4]
[1 0 1 0]


In [15]:
print(X_two_dim)
print(X_two_dim / 10)

[[1 2 3]
 [4 5 6]]
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [16]:
x = np.arange(1, 11)

print(x + 2)
print(4 * x)
print(x - 5)
print(x / 3)
print(x // 2)

[ 3  4  5  6  7  8  9 10 11 12]
[ 4  8 12 16 20 24 28 32 36 40]
[-4 -3 -2 -1  0  1  2  3  4  5]
[0.33333333 0.66666667 1.         1.33333333 1.66666667 2.
 2.33333333 2.66666667 3.         3.33333333]
[0 1 1 2 2 3 3 4 4 5]


In [17]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(f" x: {x}")
print(f" y: {y}")

x + y

 x: [1 2 3]
 y: [4 5 6]


array([5, 7, 9])

In [18]:
x * y

array([ 4, 10, 18])

In [19]:
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

X

array([[1, 2],
       [3, 4]])

In [20]:
Y

array([[5, 6],
       [7, 8]])

In [21]:
X + Y

array([[ 6,  8],
       [10, 12]])

In [22]:
X * Y

array([[ 5, 12],
       [21, 32]])

In [23]:
data = np.array([1, 2, 3, 4, 5])

print(data)
print(data.mean())
print(data.std())

[1 2 3 4 5]
3.0
1.4142135623730951


In [24]:
data = np.array([[1, 2], [1, 2]])

print(data)

[[1 2]
 [1 2]]


In [25]:
print(data.mean(axis = 0))
print(data.std(axis = 0))

[1. 2.]
[0. 0.]


In [26]:
print(data.mean(axis = 1))
print(data.std(axis = 1))

[1.5 1.5]
[0.5 0.5]


In [27]:
print(data.mean())
print(data.std())

1.5
0.5


In [28]:
X.sum(axis = 0)

array([4, 6])

In [29]:
X.sum(axis = 1)

array([3, 7])

In [30]:
X

array([[1, 2],
       [3, 4]])

In [31]:
X.sum()

10

In [32]:
X = np.array([[1, 2, 3, 4, 5],
             [6, 7, 8, 9, 10],
             [11, 12, 13, 14, 15],
             [16, 17, 18, 19, 20]])

print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [33]:
X.shape

(4, 5)

In [34]:
X.shape

(4, 5)

In [35]:
X[0, 0]

1

In [36]:
X[0][0]

1

In [37]:
X[2, 3]

14

In [38]:
X[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [39]:
X[:, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [40]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [41]:
X[1, 4]

10

In [42]:
X[:, 1]

array([ 2,  7, 12, 17])

In [43]:
X[1:3, 0:2]

array([[ 6,  7],
       [11, 12]])

In [44]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [46]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [47]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [48]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [49]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [50]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [51]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.full((2, 4), 420)

array([[420, 420, 420, 420],
       [420, 420, 420, 420]])

In [53]:
np.random.random((3, 3))

array([[0.89928981, 0.02456029, 0.11384483],
       [0.67156246, 0.1614606 , 0.00092796],
       [0.54186076, 0.66098562, 0.14352866]])

In [54]:
np.random.normal(0, 1, (3, 3))

array([[ 1.04150058,  0.27646159, -1.20205323],
       [-1.49895519,  1.21437157,  0.16323241],
       [ 0.89044103, -0.10991286,  0.51643223]])

In [55]:
np.random.randint(0, 10, (3, 3))

array([[0, 2, 8],
       [4, 7, 9],
       [4, 5, 1]])

In [56]:
np.nan

nan

In [57]:
2 + np.nan

nan

In [58]:
np.nan ** 2

nan

In [59]:
np.inf

inf

In [60]:
99999999999999999 < np.inf

True

In [62]:
-99999999999999999 > -np.inf

True

In [63]:
a = np.array([1, 0, np.nan, np.inf])

print(np.isinf(a))

print(np.isnan(a))

[False False False  True]
[False False  True False]


In [64]:
x = np.array([1, 2, 3, 4, 5])

less_than_three_mask = x < 3

less_than_three_mask

array([ True,  True, False, False, False])

In [65]:
x[less_than_three_mask]

array([1, 2])

In [66]:
even_mask = x % 2 == 0

x[even_mask]

array([2, 4])

In [67]:
x[less_than_three_mask & even_mask]

array([2])

In [68]:
x[(x < 3) & (x % 2 == 0)]

array([2])

In [70]:
x[less_than_three_mask | even_mask]

array([1, 2, 4])

In [71]:
not_div_by_2 = x % 2 != 0

x[not_div_by_2]

array([1, 3, 5])

In [72]:
x = np.arange(-5, 6)

print(x)

np.abs(x)

[-5 -4 -3 -2 -1  0  1  2  3  4  5]


array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5])

In [73]:
x = np.arange(-2, 3)

print(x)

np.sin(x)

[-2 -1  0  1  2]


array([-0.90929743, -0.84147098,  0.        ,  0.84147098,  0.90929743])

In [74]:
print(np.cos(x))

print(np.tan(x))

[-0.41614684  0.54030231  1.          0.54030231 -0.41614684]
[ 2.18503986 -1.55740772  0.          1.55740772 -2.18503986]


In [75]:
x = np.array([1, 2, 3])

np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [76]:
x = np.array([0, 1, 2, 3])

print(x)

np.exp(x)

[0 1 2 3]


array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [77]:
np.power(2, x)

array([1, 2, 4, 8])

In [78]:
#Inverse of exponentials are called logarithms, np.log gives you basic natural log

x = [1, 2, 4, 10]

print("x        = ", x)
print("ln(x)    = ", np.log(x))
print("log2(x)  = ", np.log2(x))
print("log10(x) = ", np.log10(x))


x        =  [1, 2, 4, 10]
ln(x)    =  [0.         0.69314718 1.38629436 2.30258509]
log2(x)  =  [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


In [79]:
x = np.arange(1, 6)

np.add.reduce(x)

15

In [80]:
x

array([1, 2, 3, 4, 5])

In [81]:
np.multiply.reduce(x)

120

In [82]:
L = np.random.random(100)

np.sum(L)

49.3887914564872

In [83]:
big_array = np.random.rand(1000000)

%timeit sum(big_array)

%timeit np.sum(big_array)

76.4 ms ± 2.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
203 µs ± 6.52 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [84]:
x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
x[:5]

array([0, 1, 2, 3, 4])

In [86]:
x[5:]

array([5, 6, 7, 8, 9])

In [87]:
x[-1]

9

In [88]:
x[3:5]

array([3, 4])

In [89]:
Y = np.random.randint(0, 10, (3, 3))

Y

array([[7, 8, 4],
       [2, 0, 9],
       [9, 0, 5]])

In [91]:
Y[1]

array([2, 0, 9])

In [92]:
Y[1][1]

0

In [93]:
Y[-1][-1]

5

In [94]:
x = np.array([1, 2, 3, 4, 5])

x

array([1, 2, 3, 4, 5])

In [95]:
x < 3

array([ True,  True, False, False, False])

In [96]:
x > 3

array([False, False, False,  True,  True])