In [1]:
import numpy as np

In [2]:
np?

Type:        module
String form: <module 'numpy' from '/Users/henrybutler/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
File:        ~/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>

In [4]:
a = [1, 2, 3]

a_arr = np.array(a)

a_arr

array([1, 2, 3])

In [5]:
type(a_arr)

numpy.ndarray

In [6]:
print(f'Shape: {a_arr.shape}')

print(f'Size: {a_arr.size}')

print(f'dtype: {a_arr.dtype}')

Shape: (3,)
Size: 3
dtype: int64


In [7]:
X = [[1, 2, 3], [4, 5, 6]]

X_arr = np.array(X)

X_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(f"Shape: {X_arr.shape}") # How the entries are arranged
print(f"Size: {X_arr.size}") # How many entries
print(f"dtype: {X_arr.dtype}") # What type of entries


Shape: (2, 3)
Size: 6
dtype: int64


In [9]:
# A complicated example
# ALL sublists must be the same length (in this case, length 3)

Y = [
    [[1.1, 2.3, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
]

Y_arr = np.array(Y)

Y_arr

array([[[ 1.1,  2.3,  3. ],
        [ 4. ,  5. ,  6. ]],

       [[ 7. ,  8. ,  9. ],
        [10. , 11. , 12. ]]])

In [10]:
print(f"Shape: {Y_arr.shape}") # How the entries are arranged
print(f"Size: {Y_arr.size}") # How many entries
print(f"dtype: {Y_arr.dtype}") # What type of entries


Shape: (2, 2, 3)
Size: 12
dtype: float64


In [11]:
X_one_dim = np.array([1, 2, 3, 4])

X_two_dim = np.array([[1, 2, 3,], [4, 5, 6]])

In [12]:
print(X_one_dim)
print(X_one_dim + 5)

[1 2 3 4]
[6 7 8 9]


In [13]:
print(X_one_dim)
print(X_one_dim ** 2)

[1 2 3 4]
[ 1  4  9 16]


In [14]:
print(X_one_dim)
print(X_one_dim % 2)

[1 2 3 4]
[1 0 1 0]


In [15]:
print(X_two_dim)
print(X_two_dim / 10)

[[1 2 3]
 [4 5 6]]
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [16]:
x = np.arange(1, 11)

print(x + 2)
print(4 * x)
print(x - 5)
print(x / 3)
print(x // 2)

[ 3  4  5  6  7  8  9 10 11 12]
[ 4  8 12 16 20 24 28 32 36 40]
[-4 -3 -2 -1  0  1  2  3  4  5]
[0.33333333 0.66666667 1.         1.33333333 1.66666667 2.
 2.33333333 2.66666667 3.         3.33333333]
[0 1 1 2 2 3 3 4 4 5]


In [17]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(f" x: {x}")
print(f" y: {y}")

x + y

 x: [1 2 3]
 y: [4 5 6]


array([5, 7, 9])

In [18]:
x * y

array([ 4, 10, 18])

In [19]:
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

X

array([[1, 2],
       [3, 4]])

In [20]:
Y

array([[5, 6],
       [7, 8]])

In [21]:
X + Y

array([[ 6,  8],
       [10, 12]])

In [22]:
X * Y

array([[ 5, 12],
       [21, 32]])